services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
    volumes:
      - aws_sample_dynamodb_data:/home/dynamodblocal
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set s3-minio http://minio:9000 admin123 admin123;
      /usr/bin/mc mb s3-minio/my-bucket --region=ap-northeast-1;
      /usr/bin/mc policy set public s3-minio/my-bucket;
      exit 0;
      "

volumes:
  aws_sample_dynamodb_data:
